### ISSUE TITLE
Linker exception on building for Android or iOS :(

### ISSUE THREAD

**Issue by Nelo-cool** [nuitsjp/BehaviorsForXamarinForms#10]
Hello my dear friend:)

 error MT2101: Can't resolve the reference 'Xamarin.Forms.Expander', referenced from the method 'System.Void Xamarin.Forms.BehaviorsPack.Expanders::OnTappedChanged(Xamarin.Forms.BindableObject,System.Object,System.Object)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'

P.S. Xamarin 5.0 pre5 :) 

![image](https://user-images.githubusercontent.com/902820/102711611-2c5d3680-42cc-11eb-890c-9a094c6030ed.png)
![image](https://user-images.githubusercontent.com/902820/102711623-59a9e480-42cc-11eb-9258-45b21f3d3892.png)

**Comment by Nelo-cool** [comment]
breaking changes from Microsoft maybe... :)

**Comment by Nelo-cool** [comment]
![image](https://user-images.githubusercontent.com/902820/102711715-ce7d1e80-42cc-11eb-852d-e385dbea3b1a.png)
https://forums.xamarin.com/discussion/186109/expander-in-xamarin-forms-5

**Comment by nuitsjp** [comment]
Dear Friend.
Thanks for the report.

I was not using that .NET 5 version of Xamarin yet.

If you like, you can help me?
If you can provide us with the reproduction code, we may be able to solve the problem as soon as possible.

**Comment by psharrma** [comment]
@nuitsjp ,

Any update on the fix? It is sort of blocking bug who ever is working with Xamarin Forms 5. Is it possible to have a hot fix? Should not be a major change? as the class was moved to different library:

[https://www.nuget.org/packages/Xamarin.CommunityToolkit](https://www.nuget.org/packages/Xamarin.CommunityToolkit)

**Comment by nuitsjp** [comment]
@psharrma 
Thanks for letting me know the importance of this Issue.
A hot fix has been released.
Can you please check it?
https://github.com/nuitsjp/Xamarin.Forms.BehaviorsPack/releases/tag/Release_3.0.0

**Comment by nuitsjp** [comment]
Probably not a problem, so close it once.
Please respond if you have any questions.
