### ISSUE TITLE
System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by MaxenceMax** [nuitsjp/BehaviorsForXamarinForms#2]
i got this error on iOS platform only, does iOS need to something special to work ? It seems like the method "EventToCommandBehavior" can not be found in namespace.

I don't forget : 
`xmlns:behaviorsPack="clr-namespace:Xamarin.Forms.BehaviorsPack;assembly=Xamarin.Forms.BehaviorsPack"`

and use behaviors like that : 

`<ListView.Behaviors>
                            <behaviorsPack:EventToCommandBehavior
                                EventName="ItemTapped"
                                Command="{Binding TipsTappedCommand}"/>
                        </ListView.Behaviors>`

**Comment by nuitsjp** [comment]
I think that you can solve by enabling XAML Compilation.
Classes referenced only from XAML are deleted at link time unless you enable XAML Compilation.
Please make sure XAML Compilation is enabled.
https://developer.xamarin.com/guides/xamarin-forms/xaml/xamlc/
