### ISSUE TITLE
Linking issue when using with Xamarin Forms 3.5

### ISSUE THREAD

**Issue by Gimly** [nuitsjp/BehaviorsForXamarinForms#8]
When using the library with Xamarin Forms 3.5, the linker cannot build the application correctly in release. It's probably because of the direct dependency on Xamarin.Forms 3.0.

**Comment by nuitsjp** [comment]
Thank you.
Although it became late, I applied Xamarin.Forms 3.5.0.

However, I do not understand direct dependence correctly.
I intended to set it to 3.5 or higher, is it correct?

**Comment by Gimly** [comment]
If you look at your csproj, you have a dependency on Xamarin.Forms 3.5.something. You should use instead a reference more open by using 3.5.*.

**Comment by nuitsjp** [comment]
I modified csproj as follows. Correct?

https://github.com/nuitsjp/Xamarin.Forms.BehaviorsPack/blob/master/src/Xamarin.Forms.BehaviorsPack/Xamarin.Forms.BehaviorsPack.csproj#L27

https://github.com/nuitsjp/Xamarin.Forms.BehaviorsPack/blob/master/src/Xamarin.Forms.BehaviorsPack.Tests/Xamarin.Forms.BehaviorsPack.Tests.csproj#L9

**Comment by Gimly** [comment]
It's correct for the Xamarin Forms project, but you should do the same for the ios and Android project. 

For the test project it's not necessary, but it'll make sure you're testing with the same version. So I think it's OK.

**Comment by nuitsjp** [comment]
We will close this Issue with support for Xamarin.Forms 4.8.0.
If you have any problems, please contact us again.
