### ISSUE TITLE
Can not get the URL property of WebView

### ISSUE THREAD

**Issue by shunsuke-kawai** [nuitsjp/BehaviorsForXamarinForms#9]
NullReferenceException occurs if it is described as follows.
```xml
<WebView.Behaviors>
    <behaviorsPack:EventToCommandBehavior
        Command="{Binding NavigatedCommand}"
        EventArgsPropertyPath="Url"
        EventName="Navigated" />
</WebView.Behaviors>
```

I wanted to get Url at WebView's Navigated event, but Url seems not to be a property of WebNavigatedEventArgs of Navigated's event argument class but a property of WebNavigationEventArgs which is a parent class.

Can change GetDeclaredProperty to GetProperty, is there a problem?
https://github.com/nuitsjp/Xamarin.Forms.BehaviorsPack/blob/cd05f67b6a52ae4efb05683f19aeef50cc808d9b/src/Xamarin.Forms.BehaviorsPack/CommandExecutor.cs#L36

**Comment by nuitsjp** [comment]
Thank you for your contribution!
Fix implementation to GetPropety and released Version 2.1.1.

This was a bug with the support version of .NET Standard.

GetPropety was added in .NET Standard 2.0.
This library was targeted at .NET Standard 1.0 up to 1.4. At that time, there was no GetProperty yet, so it was the above implementation.
It should have been fixed when the support target was raised to .NET Standard 2.0. But it was not corrected.

Thank you for your good point. We were able to transform into a more attractive library!
